language: python
install:
    - pip install -r requirements-test.txt
env:
  - TOX_ENV=py27
  - TOX_ENV=py34

script:
    - tox -e $TOX_ENV
script:
    - make flake8
    - make test
notifications:
    slack: luizalabs:FW6pSzZqP9dbXpBkdWwjbPDZ
